### PR TITLE
Test rspec

### PR DESCRIPTION
**Pull request by tiagorahal**
# Tic Tac Toe RSpec Testing
## Add to this project:
* ### /.rspec
* ### /.spec_helper.rb
* ### /logic_spec.rb
* ### /player_spec.rb

### CODE REVIEW

**Comment by tiagorahal** [comment]
# For the next code reviewer : 
## [Previous review](https://github.com/tiagorahal/tic-tac-toe/pull/1)

**Comment by tiagorahal** [comment]
# [Previous code reviews](https://github.com/tiagorahal/tic-tac-toe/pull/1l)

**Review by bini-i — CHANGES_REQUESTED** [review]
# Status: Requires changes :yellow_circle:      
### Hello team :wave: 

Very nice progress so far. You have done well testing all your public methods however there are required changes to be made

- [x] [Manadatory] Make sure your specs test both positive and negative scenarios
image
```
example:-

>  Check if the cell is a valid position - Should return true [positive scenario]
>  Check if the cell is an invalid position - Should return not true [negative scenario]
```

- [ ] [Optional] Including how to run the tests section in your README can help someone new to your repo to easily run the tests

#### Please work on the changes required and submit a new request once you are ready!

#### If you have any question kindly reach me on slack @Binyam Hailemeskel

### HAPPY CODING :computer: :blush: 

> #### Reviewed by Binyam Hailemeskel (Part-Time TSE)
> GitHub: [@bini-i](https://github.com/bini-i) 
> Twitter: [@binyamshewa](https://twitter.com/binyamshewa)
> LinkedIn: [LinkedIn](https://www.linkedin.com/in/binyam-hailemeskel-728048151/)

**Review by MkrtichSargsyan — CHANGES_REQUESTED** [review]
## _Status:_ Changes Requested :recycle:

Good job on implementing the changes requested. However, there are some changes that you need to make in order to get your project approved


- [x] Kindly test also for negative scenarios 
  For example, you can use similar tests

      it 'should now create instance of Player' do
        expect({ name: 'John', letter: 'X' }).not_to be_an_instance_of(Player)
      end

      it 'should not return an empty board' do
        expect(game_logic.show_board).not_to eq("+------+---+\n| 1 | 2 | 3 |\n+---+---+---+\n| 4 | 5 | 6 |\n+---+---+---+\n| 7 | 8 | 9 |\n+---+---+---+\n\n")
      end


- [x] Kindly fix this rubocop issue





Please, make the REQUIRED changes and submit your request again! :grinning:
Good luck. 

> ps: . If you have any questions about my review or need help, you can message me on slack ( @mkrtichsargsyan )

**Review by BrianSammit — APPROVED** [review]
STATUS: APPROVED  💪 💯 
----------- 
Hello @tiagorahal  You did an amazing job in this project 👏 great job working on the required changes 👍 
----------
Now you can merge this branch 💯 
Reach me on SLACK if you have any questions. 
@ Brian Sammit Cruz Rodrguez
HAPPY CODING!! AND GOOD LUCK 🤞 🍀 

gif-good-job

**Pull request merged**
